### ISSUE TITLE
not working ngClick

### ISSUE THREAD

**Issue by wormen** [teropa/angular-virtual-dom#13]
I wrote earlier that you do not work in v-root user directive, as it turned out, the standard also does not want to work

**Comment by teropa** [comment]
Directives need to be "virtual DOM aware" in order to work with this library, as described in #12.

Standard directives, such as ngClick, expect a concrete DOM and do not work with a virtual DOM, so they cannot be directly used within a v-root. There is an experimental vClick directive in the "events" branch of this repo, which replaces ngClick.

**Comment by wormen** [comment]
vClick I just tried to use, but I have not worked and this directive

**Comment by teropa** [comment]
Can you post an example of code that isn't working?

**Comment by wormen** [comment]
```
<ul class="nav sidebar-nav" v-root="Menu">
        <li v-repeat="M in Menu">
            <a href="{{M.uri}}" class="{{M.class}}" target="{{M.target}}" v-click="FixSetItem(M.id,0,M.hasChild)">
                <span class="{{M.ico}}"></span>
                <span class="sidebar-title">{{M.title}}</span>
                <span class="caret" ng-show="M.hasChild"></span>
            </a>
        </li>
    </ul>
```
